---
title: "My first dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library (dplyr)
library(p8105.datasets)
library(flexdashboard)
library(viridis)
library(plotly)
library(patchwork)


rm(list = ls())

knitr::opts_chunk$set(
    echo = TRUE,
    warning = FALSE,
    fig.width = 10, 
  fig.height = 8,
  out.width = "100%"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(tibble.print_min = 3)
```

```{r load_dataset}
set.seed(1)
noaa = p8105.datasets::ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  filter(!is.na(tmax), !is.na(tmin), !is.na(snow), !is.na(snwd), !is.na(prcp)) %>% 
  mutate(pcrp = prcp / 10,
         tmax = as.integer(tmax)/ 10,
         tmin = as.integer(tmin)/ 10,
         year = as.integer(year),
         month = as.integer(month),
         day = as.integer(day)) 
head(noaa,3)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
Scatter plot: 

```{r}
scatter_plot = noaa %>% 
  filter(year == 2005:2010)

scatter_plot %>% 
  plot_ly(x = ~tmax, y = ~tmin, type = "scatter", mode = "markers",
          color = ~year, alpha = 0.5) %>% 
  layout(title = "Max Temperatures vs Min Temperatures in New York from Year 2005 to 2010")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B
Bar plots

```{r}
noaa %>%
  filter(year == 2010 & month == 2) %>% 
  group_by(day) %>% 
  select(day, snow, snwd) %>% 
  summarise(snow_mean = mean(snow),
         snwd_mean = mean(snwd)) %>% 
  plot_ly(x = ~day, y = ~snow_mean, type = "bar", name = "Snowfall") %>%
  add_trace(y = ~snwd_mean, name = "Snow depth") %>%
  layout(yaxis = list(title = 'mm'), barmode = 'stack') %>% 
  layout(title = "Average Snowfall and Snowdepth in Feb. 2010 in New York")
```


### Chart C
Line plots:

```{r}
Year = c(2005:2010)

Feb = 
  noaa %>% 
      filter(month == 2) %>% 
      group_by(month, year) %>% 
      summarise(mean_temp = mean(tmax))

Aug = 
  noaa %>% 
    filter(month == 8) %>% 
    group_by(month, year) %>% 
    summarise(mean_temp = mean(tmax))

df = data.frame(Year, Feb, Aug)

plot_ly(df, x = ~Year, y = ~Feb$mean_temp, name = 'Feburary', type = 'scatter', mode = 'lines') %>% 
  add_trace(y = ~Aug$mean_temp, name = 'August', mode = 'lines+markers') %>% 
  layout(title = "Average Max Temperatures for Feburary and August in New York from 2005 to 2010")
```
